"""Stub de tipos para rustodbc.

Escrito a mano (no generado): la superficie publica es chica (~40 simbolos
una vez completa) y un stub a mano documenta la API mejor que lo que
generan hoy las herramientas para AsyncIterator/overloads/Self sobre PyO3.

Fase 0: solo la seccion "implementado" existe realmente en `._rustodbc`. El
resto queda como referencia de diseno (AGENTS.md ss "API publica" es la
fuente de verdad) para no perder la forma acordada mientras se implementa.
"""

from collections.abc import AsyncIterator, Mapping, Sequence
from decimal import Decimal
from datetime import date, datetime, time
from types import TracebackType
from typing import Any, Literal, Self, TypeAlias

__version__: str

Value: TypeAlias = str | int | float | Decimal | bool | bytes | date | time | datetime | None
Row: TypeAlias = dict[str, Value]
Params: TypeAlias = Sequence[Value] | Mapping[str, Value] | None
DecimalMode: TypeAlias = Literal["decimal", "str", "float"]
NoPkPolicy: TypeAlias = Literal["insert", "error"]

# ------------------------------- implementado -------------------------------

def load_dotenv(path: str | None = ...) -> bool: ...

class Credentials:
    # None solo cuando la instancia viene de `from_connection_string`.
    system: str | None
    user: str | None
    driver: str | None

    def __init__(self, *, system: str, user: str, password: str, driver: str | None = ...) -> None: ...
    @classmethod
    def from_env(cls, client_code: str, environment: str | None = ...) -> Self: ...
    @classmethod
    def from_dsn(cls, dsn: str) -> Self: ...
    @classmethod
    def from_connection_string(cls, dsn: str) -> Self: ...

class EngineOptions:
    pool_size: int
    login_timeout: int
    query_timeout: int
    batch_size: int
    max_workers: int
    min_rows_per_worker: int
    merge_chunk_size: int
    merge_max_workers: int
    stream_batch_size: int
    prefetch_batches: int
    decimal_mode: DecimalMode
    strip_char_padding: bool
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def from_env(cls) -> Self: ...

class RustOdbcError(Exception):
    message: str
    sqlstate: str | None
    native_code: int | None
class ConfigurationError(RustOdbcError): ...
class ConnectError(RustOdbcError): ...
class PoolTimeout(ConnectError): ...
class InterfaceError(RustOdbcError): ...
class QueryError(RustOdbcError): ...
class SqlSyntaxError(QueryError): ...
class IntegrityError(QueryError): ...
class DataError(QueryError): ...
class OperationTimeout(QueryError): ...
class ParameterError(RustOdbcError): ...
class BulkFailure(RustOdbcError): ...
class MergeFailure(RustOdbcError): ...
class CatalogError(RustOdbcError): ...
class FeatureUnavailable(RustOdbcError): ...

# ------------------------------- implementado (Fase 1+) ----------------------

class Db2iEngine:
    @staticmethod
    async def connect(credentials: Credentials, options: EngineOptions | None = ...) -> Self: ...
    @staticmethod
    async def from_env(client_code: str, environment: str | None = ...,
                       options: EngineOptions | None = ...) -> Self: ...
    def close(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, et: type[BaseException] | None, e: BaseException | None,
                         tb: TracebackType | None) -> bool: ...
    async def execute(self, sql: str, params: Params = ...) -> int: ...
    async def fetch_all(self, sql: str, params: Params = ...) -> list[Row]: ...
    async def fetch_one(self, sql: str, params: Params = ...) -> Row | None: ...
    async def fetch_value(self, sql: str, params: Params = ...) -> Value: ...
    async def fetch_column(self, sql: str, params: Params = ...) -> list[Value]: ...
    def stream_batches(self, sql: str, params: Params = ...,
                        batch_size: int | None = ...) -> "BatchStream": ...
    def stream(self, sql: str, params: Params = ...,
               batch_size: int | None = ...) -> "BatchStream": ...
    async def executebatch(self, sql: str, rows: Sequence[Sequence[Value]]) -> BulkReport: ...
    async def call_proc(self, schema: str, proc: str,
                         params: Mapping[str, Value] | None = ...) -> "ProcResult": ...
    def table_sync(self, source: "Db2iEngine | None" = ...) -> "TableSync": ...

class BatchStream:
    @property
    def columns(self) -> list[str]: ...
    def __aiter__(self) -> "BatchStream": ...
    async def __anext__(self) -> list[Row]: ...
    async def __aenter__(self) -> "BatchStream": ...
    async def __aexit__(self, et: type[BaseException] | None, e: BaseException | None,
                         tb: TracebackType | None) -> None: ...
    def cancel(self) -> None: ...
    async def aclose(self) -> None: ...

class BulkReport:
    rows_affected: int
    batches: int

class TaskFailure:
    index: int
    error: str

class ParallelReport:
    rows_affected: int
    failures: list[TaskFailure]

def plan_concurrency(total_rows: int, min_rows_per_worker: int, max_workers: int) -> int: ...

class ProcResult:
    result_sets: list[list[Row]]
    out_params: dict[str, Value]

class MergeReport:
    rows_affected: int
    batches: int
    used_merge: bool
    warning: str | None

class TableSync:
    async def merge(self, schema: str, table: str, records: Sequence[Row],
                     primary_key: Sequence[str] | None = ...) -> MergeReport: ...
    def merge_sync(self, schema: str, table: str, records: Sequence[Row],
                   primary_key: Sequence[str] | None = ...) -> MergeReport: ...

# --------------------------- diseno, no implementado -------------------------
# Ver AGENTS.md ss "API publica".
#
# class ConnectionLease: ...
# class Transaction: ...

# ------------------------------- rustodbc.blocking ---------------------------
# Se importa por submodulo explicito: `from rustodbc.blocking import BlockingEngine`.

class BlockingEngine:
    @staticmethod
    def connect(credentials: Credentials, options: EngineOptions | None = ...) -> Self: ...
    @staticmethod
    def from_env(client_code: str, environment: str | None = ...,
                 options: EngineOptions | None = ...) -> Self: ...
    def close(self) -> None: ...
    def execute(self, sql: str, params: Params = ...) -> int: ...
    def fetch_all(self, sql: str, params: Params = ...) -> list[Row]: ...
    def fetch_one(self, sql: str, params: Params = ...) -> Row | None: ...
    def fetch_value(self, sql: str, params: Params = ...) -> Value: ...
    def fetch_column(self, sql: str, params: Params = ...) -> list[Value]: ...
    def stream(self, sql: str, params: Params = ...,
               batch_size: int | None = ...) -> "BlockingBatchStream": ...
    def executebatch(self, sql: str, rows: Sequence[Sequence[Value]]) -> BulkReport: ...
    def call_proc(self, schema: str, proc: str,
                  params: Mapping[str, Value] | None = ...) -> "ProcResult": ...
    def table_sync(self, source: "BlockingEngine | None" = ...) -> "TableSync": ...

class BlockingBatchStream:
    @property
    def columns(self) -> list[str]: ...
    def __iter__(self) -> "BlockingBatchStream": ...
    def __next__(self) -> list[Row]: ...
